version: '3.8'

services:
  angular:
    container_name: angular-dev
    build:
      context: .
      dockerfile: DockerFile
    image: dev
    ports:
      - "4200:4200"
      - "3000:3000"
      - "80:3000"
    volumes:
      - .:/app
    working_dir: /app
    # depends on mongo
    depends_on: [mongo]
    cpu_percent: 50
    mem_limit: 256m

    # command: npm run dev
    # replicas: 3

  prod:
    container_name: angular-prod
    build:
      context: .
      dockerfile: DockerFile
    image: prod
    ports:
      - "4200:4200"
      - "3000:3000"
      - "80:3000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on: [mongo]
    command: npm run start
    profiles:
      - "prod"
    cpu_percent: 50
    mem_limit: 256m

  mongo:
    container_name: mongo-db
    image: mongo:4.4.4
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  